#!/bin/bash

# printf formatting
export ERROR='\033[1;31m'    # Brown/Orange
export WARNING='\033[1;33m'  # Yellow
export NC='\033[0m'          # No Color

# K8s context
export CONTEXT=default_context

# K8s namespace
export NAMESPACE=default_namespace

# variables used in image path
export IMAGE_PATH_ROOT="eu.gcr.io/default-assets"

# application name inherited from git repo
APP=$(basename "$PWD")
export APP

# unique team identifier will be appended to image name
export BRANCH=uat
